project:
  type: book

book:
  title: "確率・統計入門"
  author: "Ryuhei Mori"
  date: last-modified
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: "確率論"
      chapters:
        - intro.qmd
        - prob-space.qmd
    - part: "統計学"
      chapters:
        - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc-title: "目次"
  pdf:
    pdf-engine: lualatex
    pdf-engine-opts:
      - '--no-shell-escape'
      - '--halt-on-error'
    documentclass: ltjsreport
    classoption: [a4paper]
    papersize: a4paper
    include-in-header:
      text: |
        \usepackage{mathtools}
    toc-title: "目次"

execute:
  freeze: auto


