# マルコフ連鎖

## 確率過程とマルコフ連鎖
共通の確率空間 $(\Omega,\,P)$ 上の長さ無限の確率変数列 $X_0,X_1,X_2,\dotsc$ を**離散時間確率過程**という。
各時刻 $t=0,1,2,\dotsc,$ について、 $X_t$ を時刻 $t$ における状態と考える。
離散時間確率過程 $X_0,X_1,\dotsc,$ の各確率変数の像が**有限集合** $S$ であり、
任意の $t\in\mathbb{Z}_{\ge 0}$ と $x_0,\dotsc, x_{t+1}\in S$ について
\begin{align*}
\Pr(X_{t+1} = x_{t+1}\mid X_{t} = x_t,\dotsc,\,X_1=x_1,\,X_0=x_0)
&= \Pr(X_{t+1} = x\mid X_{t} = x_t)
\end{align*}
を満たすとき、それを**有限状態マルコフ連鎖**という。
さらに、
\begin{align*}
\Pr(X_{t+1} = x_{t+1}\mid X_{t} = x_t)
\end{align*}
が $t\in\mathbb{Z}_{\ge 0}$ に依存しないとき**時間的に均一な有限状態マルコフ連鎖**という。
以下では時間的に均一な有限状態マルコフ連鎖を考える。

## 確率行列と状態遷移図

有限状態マルコフ連鎖の場合、状態 $S$ は実数の有限部分集合と考えるより、単に有限集合と考えた方が自然な場合も多い。
例えば $S = \{ 晴れ、曇り、雨\}$ や。
このとき、状態集合を便宜上 $S=\{1,2,\dotsc,n\}$ とおき、
\begin{align*}
p_{i,j} &= \Pr(X_{t+1} = j\mid X_{t} = i)\qquad \forall i,\,j\in S
\end{align*}
とする。
この $p_{i,j}$ を $(i,j)$ 成分に持つ $n\times n$ 行列 $T$ を**遷移行列**という。
遷移行列は非負行列であり、行和が1である。
一般に、この二つの条件を満たす正方行列を**確率行列**という。
確率行列は遷移行列とみなすことができる。

一方で、初期確率からなる行ベクトル $\pi\in\mathbb{R}^{|S|}$ を**初期状態ベクトル**という。
つまり、行ベクトル $\pi$ の $i\in S$ 成分を $\pi_i$ とすると、
\begin{align*}
\pi_i &= \Pr(X_0=i)\qquad i\in S
\end{align*}
である。

初期状態ベクトル $\pi$ と確率行列 $T$ からマルコフ連鎖は定義される。

:::{#exm-whether}
### 天気のマルコフ連鎖

状態集合 $S=\{晴れ、曇り、雨\}$ 上のマルコフ連鎖を考える。
\begin{align*}
\Pr(X_0 = 晴れ) &= 1/3\\
\Pr(X_0 = 曇り) &= 1/2\\
\Pr(X_0 = 雨) &= 1/6\\
\Pr(X_{t+1} = 晴れ\mid X_t=晴れ) &= 1/2\\
\Pr(X_{t+1} = 曇り\mid X_t=晴れ) &= 1/3\\
\Pr(X_{t+1} = 雨\mid X_t=晴れ) &= 1/6\\
\Pr(X_{t+1} = 晴れ\mid X_t=曇り) &= 1/4\\
\Pr(X_{t+1} = 曇り\mid X_t=曇り) &= 1/2\\
\Pr(X_{t+1} = 雨\mid X_t=曇り) &= 1/4\\
\Pr(X_{t+1} = 晴れ\mid X_t=雨) &= 1/3\\
\Pr(X_{t+1} = 曇り\mid X_t=雨) &= 1/3\\
\Pr(X_{t+1} = 雨\mid X_t=雨) &= 1/3\\
\end{align*}
と初期確率と遷移確率が与えられているとする。
このとき、
\begin{align*}
晴れ&\longleftrightarrow 1&
曇り&\longleftrightarrow 2&
雨&\longleftrightarrow 3&
\end{align*}
と対応させると、初期状態ベクトル $\pi$ と遷移行列 $T$ は
\begin{align*}
\pi&=
\begin{bmatrix}
1/3&1/2&1/6
\end{bmatrix}&
T&=
\begin{bmatrix}
1/2&1/3&1/6\\
1/4&1/2&1/4\\
1/3&1/3&1/3
\end{bmatrix}
\end{align*}
である。
:::

確率の遷移確率を有向グラフで表したものを**状態遷移図**という。
上記の天気のマルコフ連鎖の状態遷移図は以下の通りである。
状態遷移図において遷移確率が0の有向辺は通常は描かない。

```{dot}
digraph Markov {
  rankdir=LR;
  node [shape=circle, width=0.5, height=0.5, fontsize=7];

  1 [label="晴れ"]
  2 [label="曇り"]
  3 [label="雨"]

  1 -> 1 [label="1/2"];
  1 -> 2 [label="1/3"];
  1 -> 3 [label="1/6"];

  2 -> 1 [label="1/4"];
  2 -> 2 [label="1/2"];
  2 -> 3 [label="1/4"];

  3 -> 1 [label="1/3"];
  3 -> 2 [label="1/3"];
  3 -> 3 [label="1/3"];
}
```


## 時刻 $t$ の確率分布
初期状態ベクトル $\pi$ と遷移行列 $T$ が与えられているとき、$X_1$ の確率は
\begin{align*}
\Pr(X_1=j) &= \sum_{i\in S} \Pr(X_0=i) \Pr(X_1=j\mid X_0=i)\\
&=\sum_{i\in S} \pi_i\, p_{i, j}\\
&=(\pi T)_j
\end{align*}
と表せる。よって、
\begin{align*}
\Pr(X_t=j) &= (\pi T^t)_j
\end{align*}
である。

任意の遷移行列 $T$ とすべて1の列ベクトル $\mathrm{1}\in\mathbb{R}^{|S|}$ について、
\begin{align*}
T \mathrm{1} = \mathrm{1}
\end{align*}
である。
<!-- よって $T$ は固有値1を持つ。-->
よって $I-T$ は正則ではないので固有値1を持ち、対応する左固有ベクトル $\mu$ を持つ。
つまり、
\begin{align*}
\mu T = \mu
\end{align*}
を満たす非零行ベクトル $\mu$ が存在する。
非負で成分の和が1の行ベクトル $\mu$ で $\mu T = \mu$ を満たすものを**定常確率ベクトル**もしくは**定常分布**という。
現時点では定常確率ベクトルの存在は明らかではないが、任意の遷移行列 $T$ について定常確率ベクトルが存在する。

:::{.callout-note}
以下の不動点定理を認めると、定常確率ベクトルの存在が直ちに証明できる。

**ブラウワーの不動点定理**: ユークリッド空間のコンパクト凸集合 $K$ からそれ自身への連続関数は不動点を持つ。

$K$ を非負で成分の和が1のベクトルの集合とおけばよい。$T$ を右から掛けるという写像は連続写像なのでブラウワーの不動点定理が適用できる。
:::

:::{#exm-whether-stab}
### 天気のマルコフ連鎖の定常確率ベクトル
\begin{align*}
T&=
\begin{bmatrix}
1/2&1/3&1/6\\
1/4&1/2&1/4\\
1/3&1/3&1/3
\end{bmatrix}
\end{align*}
のとき、
\begin{align*}
I-T&=
\begin{bmatrix}
1/2&-1/3&-1/6\\
-1/4&1/2&-1/4\\
-1/3&-1/3&2/3
\end{bmatrix}
\end{align*}
の左カーネルとして
\begin{align*}
\mu&=
\begin{bmatrix}
9/25&2/5&6/25
\end{bmatrix}
\end{align*}
が取れる。これは非負で成分の和が1なので、定常確率ベクトルである。
$I-T$ のランクは2であり、これが唯一の定常確率ベクトルである。

一方で、この例においては $T$ を対角化することはできない。
:::

<!--
この確率について、

1. もっと単純な数式で表す。
1. 効率的なアルゴリズムを与える。
1. $n\to\infty$ の漸近

遷移行列 $T$ が $T=UDU^{-1}$ と対角化できるとき、
-->

::: {#def-spectral}
### スペクトル半径
正方行列 $A\in\mathbb{C}^{n\times n}$ について、その固有値の絶対値の最大値を**スペクトル半径**といい $\rho(A)$ で表す。
:::

::: {.callout-caution}
**スペクトルノルム**はスペクトル半径と似た概念であるが異なるものである。
正方行列とは限らない行列 $A\in\mathbb{C}^{n\times m}$ のスペクトルノルムは
\begin{align*}
\|A\|_2&\coloneqq \max_{x\in\mathbb{C}^m \setminus\{0\}} \frac{\|Ax\|_2}{\|x\|_2}
\end{align*}
と定義される。
ここで、右辺の $\|\cdot\|_2$ は複素ユークリッド空間上の **$L_2$ ノルム**を表す。ここで、
\begin{align*}
\|A\|_2&=
\max_{x\in\mathbb{C}^m \setminus\{0\}} \left\|A\frac{x}{\|x\|_2}\right\|_2\\
&=\max_{x\in\mathbb{C}^m\colon\, \|x\|_2=1} \left\|Ax\right\|_2\\
&=\max_{x\in\mathbb{C}^m\colon\, \|x\|_2=1} \sqrt{\left\|Ax\right\|_2^2}\\
&=\sqrt{\max_{x\in\mathbb{C}^m\colon\, \|x\|_2=1} x^*A^*Ax}\\
&=\sqrt{\lambda_{\max}(A^*A)}\\
&=\sigma_{\max}(A)
\end{align*}
である。$\lambda_{\max}$ と $\sigma_{\max}$ は最大固有値と最大特異値を表す。

直感的な意味としては

* スペクトルノルム$\colon$ 線形写像 $A$ が $L_2$ ノルムをどれだけ大きくするか？
* スペクトル半径 $\colon$ 線形写像 $A$ が**向きを変えずに** $L_2$ ノルムをどれだけ大きくするか？

ということになる。
これらの意味から $\|A\|_2\ge\rho(A)$ であることが分かる。
実際 $\|A\|_2$ の定義の中で $x$ として $A$ の絶対値最大固有値に対応する固有ベクトルを選べばこの不等式が得られる。

正方行列 $A\in\mathbb{C}^{n\times n}$ が**正規行列**のとき、スペクトル分解定理よりユニタリ行列 $U$ と対角行列 $D$ を用いて $A = UDU^*$ と表せる。
このとき、$A^*A=UD^*DU^*$ であることから、簡単な計算により $\|A\|_2=\rho(A)$ であることが分かる。

しかし一般的には(対角化可能であっても)スペクトル半径とスペクトルノルムは異なる。
例えば、
\begin{align*}
A&=\begin{bmatrix}
1&0\\
1&0
\end{bmatrix}
\end{align*}
とすると、 $A$ の固有値は 0 と 1 なので$\rho(A)=1$ である。
一方で、
\begin{align*}
A^*A&=
\begin{bmatrix}
2&0\\
0&0
\end{bmatrix}
\end{align*}
より、$A^*A$ の固有値は 0 と 2 である。
よって、$A$ のスペクトルノルムは $\|A\|_2=\sqrt{2} > 1 =\rho(A)$ である。
ここで、$A$ は確率行列であり、二つの異なる固有値を持つので対角化可能である。

また、スペクトル半径はノルムにもならない。
\begin{align*}
\rho\left(\begin{bmatrix}0&1\\0&0\end{bmatrix}\right) &= 0
\end{align*}
であるし、
\begin{align*}
1&=\rho\left(\begin{bmatrix}0&1\\1&0\end{bmatrix}\right) >
\rho\left(\begin{bmatrix}0&1\\0&0\end{bmatrix}\right) +
\rho\left(\begin{bmatrix}0&0\\1&0\end{bmatrix}\right) = 0
\end{align*}
なので三角不等式も満たさない。
:::

::: {#lem-spectral}
任意の確率行列 $T$ について、$\rho(T)=1$ である。
:::
::: {.proof}
すべての成分が1の列ベクトルは確率行列 $T$ の固有値1に対する右固有ベクトルになるので、$\rho(T)\ge 1$ である。

以下では $\rho(T)\le 1$ を示す。
遷移行列 $T$ の固有値 $\lambda\in\mathbb{C}$ に対応する固有ベクトルを $v$ とすると
\begin{align*}
Tv &= \lambda v
\end{align*}
が成り立つ。
$v$ の成分で絶対値最大のものを第 $i$ 成分とする。
第 $i$ 成分に注目すると
\begin{align*}
\sum_{j\in S}T_{i,j}v_j &= \lambda v_i
\end{align*}
が成り立つ。ここで
\begin{align*}
|\lambda| |v_i| &= \left|\sum_{j\in S}T_{i,j}v_j\right|\\
&\le \sum_{j\in S}T_{i,j}\left|v_j\right|\\
&\le \sum_{j\in S}T_{i,j}\left|v_i\right|\\
&=\left|v_i\right|
\end{align*}
と $|v_i|>0$ より、 $|\lambda|\le 1$ である。
:::


## マルコフ連鎖の例: グラフ上のランダムウォーク
:::{#def-graph}
### グラフ
有限集合 $V$ と集合 $E\subseteq \{\{u,v\}\mid u,\, v\in V, u\ne v\}$ のペア $G=(V,\,E)$ を(無向単純)グラフという。
$V$ の元を**頂点**、$E$ の元を**辺**と呼ぶ。
:::

グラフ $G=(V,\,E)$ と $v\in V$ について、
\begin{align*}
N(v)&\coloneqq\{u\in V\mid \{u,v\}\in E\}
\end{align*}
を頂点 $v$ の**近傍**という。また、
\begin{align*}
d_v&\coloneqq|N(v)|
\end{align*}
を $v$ の**次数**という。
次数0の頂点を**孤立頂点**という。

:::{#def-rw}
### グラフ上のランダムウォーク
孤立頂点を持たないグラフ $G=(V=\{1,2,\dotsc,n\},\,E)$ 上のランダムウォークは $S=V$ であり、
任意の初期確率ベクトル $\pi$ と
\begin{align*}
p_{i,j} &=
\begin{cases}
 \frac1{d_i}&\text{if } \{i,j\}\in E\\
 0&\text{otherwise}
\end{cases}
\end{align*}
で定義される。
:::

:::{#lem-rw}
グラフ上のランダムウォークの遷移行列は対角化可能であり、固有値はすべて実数である。
:::
:::{.proof}
グラフ $G$ の次数行列を
\begin{align*}
D_{i,j} &= d_i\delta_{i,j}
\end{align*}
と定義する。
ここで $\delta_{i,j}$ はクロネッカーのデルタである。
\begin{align*}
Q &= \sqrt{D} P \sqrt{D}^{-1}
\end{align*}
とすると、その $(i,j)$ 成分は
\begin{align*}
Q_{i,j} &= \sqrt{d_i} p_{i,j} \frac1{\sqrt{d_j}}\\
 &= \begin{cases}
 \sqrt{d_i} \frac1{d_i} \frac1{\sqrt{d_j}} = \frac1{\sqrt{d_id_j}}&\text{if } \{i,j\}\in E\\
 0&\text{otherwise}
 \end{cases}
\end{align*}
である。よって$Q$ は実対称行列であり、スペクトル分解定理より、直交行列で対角化でき、すべての固有値は実数である。
つまり、ある直交行列 $V$ と実対角行列 $\Lambda$ が存在して
\begin{align*}
Q &= V\Lambda V^T
\end{align*}
である。
よって、
\begin{align*}
P &= \sqrt{D}^{-1}Q\sqrt{D} = \sqrt{D}^{-1}V\Lambda V^T\sqrt{D}
\end{align*}
が成り立ち、$P$ も対角化可能であり、固有値はすべて実数である。
:::

$T=U\Lambda U^{-1}$ と対角化できるとき、$t$ ステップ後の確率は
\begin{align*}
\pi T^t &= \pi (U \Lambda U^{-1})^t\\
&= \pi U \Lambda^t U^{-1}
\end{align*}
と表せる。
$T$ の固有値の絶対値は 1 以下であるので、グラフ上のランダムウォークの場合、$t\to\infty$ 極限では $\Lambda^t$ は固有値 $\pm1$ の部分だけが残る。
特に**固有値1が一つだけであり、固有値 $-1$ を持たないとき**、初期分布 $\pi$ によらず、唯一の定常分布 $\mu$ に収束する。
\begin{align*}
\lim_{t\to\infty} \pi T^t  &= \mu
\end{align*}

:::{#lem-graph-eigen}
グラフ上のランダムウォークの遷移行列 $T$ に含まれる固有値1の重複度はグラフの**連結成分の個数**である。
:::
:::{.proof}
まず、「固有値1の重複度 $\ge$ グラフの連結成分の個数」を証明する。
グラフの連結成分 $C\subseteq V$ について、列ベクトル $\mathrm{1}_C$ を成分のインデックスが $C$ に含まれるとき1、そうでないとき 0 と定義する。
このとき、$T\mathrm{1}_C=\mathrm{1}_C$ であるので、固有値1の右固有ベクトルとなる。
各連結成分 $C$ について $\mathrm{1}_C$ は線形独立であるので、「固有値1の重複度 $\ge$ グラフの連結成分の個数」が示された。

次に、「固有値1の重複度 $\le$ グラフの連結成分の個数」を証明する。
$v$ を固有値1に対応する固有ベクトルとすると、
\begin{align*}
Tv &=  v
\end{align*}
が成り立つ。
これは
\begin{align*}
\sum_{j\in S}T_{i,j} v_j &=  v_i\qquad\forall i\in V
\end{align*}
を意味する。
グラフの連結成分 $C\subseteq V$ を固定する。
そして、
\begin{align*}
i &\in \arg\max_{j\in C} v_j
\end{align*}
とする。
このとき、
\begin{align*}
v_i &= \sum_{j\in S}T_{i,j} v_j\\
&\le \sum_{j\in S}T_{i,j} v_i\\
&= v_i
\end{align*}
という不等式が得られるが、この不等式が等号で満たされなければならない。
よって、$j\in N(i)$ について $v_j=v_i$ であることが必要である。
よって $j\in C$ について $v_j=v_i$ である必要がある。
したがって、グラフの連結成分を $C_1,\dotsc,C_k$ とすると
\begin{align*}
v&\in\mathrm{span}(\mathrm{1}_{C_1},\dotsc,\mathrm{1}_{C_k})
\end{align*}
である。
以上のことから「固有値1の重複度 $\le$ グラフの連結成分の個数」が示された。
:::

:::{#lem-graph-eigenb}
グラフ上のランダムウォークの遷移行列 $T$ に含まれる固有値 $-1$ の重複度はグラフの**二部連結成分の個数**である。
:::
:::{.proof}
まず、「固有値  $-1$ の重複度 $\ge$ グラフの二部連結成分の個数」を証明する。
グラフの二部連結成分 $L\cup R\subseteq V$ について、列ベクトル $\mathrm{1}_{L,R}$ を成分のインデックスが $L$ に含まれるとき $+1$、$R$ に含まれるとき $-1$、それ以外のとき 0 と定義する。
このとき、$T\mathrm{1}_{L,R}=-\mathrm{1}_{L,R}$ であるので、固有値$-1$の右固有ベクトルとなる。
各二部連結成分 $L\cup R$ について $\mathrm{1}_{L,R}$ は線形独立であるので、「固有値 $-1$ の重複度 $\ge$ グラフの二部連結成分の個数」が示された。

次に、「固有値 $-1$ の重複度 $\le$ グラフの二部連結成分の個数」を証明する。
$v$ を固有値 $-1$ に対応する固有ベクトルとすると、
\begin{align*}
Tv &=  -v
\end{align*}
が成り立つ。
これは
\begin{align*}
\sum_{j\in S}T_{i,j} v_j &=  -v_i\qquad\forall i\in V
\end{align*}
を意味する。
グラフの二部連結成分 $L\cup R\subseteq V$ を固定する。
そして、
\begin{align*}
i &\in \arg\max_{j\in L\cup R} |v_j|
\end{align*}
とする。
このとき、
\begin{align*}
-v_i &= \sum_{j\in S}T_{i,j} v_j\\
&\le \sum_{j\in S}T_{i,j} |v_i|\\
&= |v_i|
\end{align*}
という不等式が得られるが、$v_i\le 0$ のとき、この不等式が等号で満たされなければならない。
よって、$v_i\le 0$ のとき、$j\in N(i)$ について $v_j=-v_i$ であることが必要である。
同様に、
\begin{align*}
-v_i &= \sum_{j\in S}T_{i,j} v_j\\
&\ge -\sum_{j\in S}T_{i,j} |v_i|\\
&= -|v_i|
\end{align*}
より、$v_i\ge 0$ のときも、$j\in N(i)$ について $v_j=-v_i$ であることが必要である。
よって $j\in L\cup R$ について
\begin{align*}
v_j&=\begin{cases}
v_i&\text{if } \{i,j\}\subseteq L\text{ or } \{i,j\}\subseteq R\\
-v_i&\text{otherwise}
\end{cases}
\end{align*}
 である必要がある。
したがって、グラフの二部連結成分を $L_1\cup R_1,\dotsc,L_k\cup R_k$ とすると
\begin{align*}
v&\in\mathrm{span}(\mathrm{1}_{L_1,R_1},\dotsc,\mathrm{1}_{L_k,R_k})
\end{align*}
である。
以上のことから「固有値 $-1$ の重複度 $\le$ グラフの二部連結成分の個数」が示された。
:::

よって、グラフが**連結していて二部グラフでない**場合は遷移行列は固有値 $1$ を一つだけ持ち、固有値 $-1$ を持たない。
この場合は、初期分布 $\pi$ によらず、唯一の定常分布に収束する。
<!--
## 確率の計算アルゴリズム

:::{#def-fps}
### 形式的冪級数
:::

時刻 $n$ で状態 $j$ の確率
\begin{align*}
\Pr(X_n=j) &= (\pi T^n)_j
\end{align*}
を計算するアルゴリズムを考える。
\begin{align*}
\Pr(X_n=j) &= (\pi T^n)_j\\
&= \left( [x^n] \sum_{t\ge 0}\pi T^t x^t\right)_j
\end{align*}
-->
