# 複数の確率変数

## 事象の条件付き確率と独立性

::: {#def-cond}
### 条件付き確率

確率空間 $(\Omega,\,P)$ の事象 $A,B\subseteq\Omega$ について
$P(B)> 0$ のとき、**$B$ における $A$ の条件付き確率** は以下で定義される。
\begin{align*}
P(A\mid B) &\coloneqq \frac{P(A\cap B)}{P(B)}.
\end{align*}
:::

二つの事象 $A,B\subseteq\Omega$ を考える文脈では $P(A\cap B)$ を**同時確率**、$P(A),\,P(B)$ を**周辺確率**という。

::: {#def-ind}
### 事象の独立性

確率空間 $(\Omega,\,P)$ の事象 $A,B\subseteq\Omega$ について
\begin{align*}
P(A\cap B) &= P(A) P(B)
\end{align*}
を満たすとき、**事象 $A$ と $B$ は独立である**という。
:::

::: {#exm-ind}
### 二回のコイン投げ
標本空間を $\Omega = \{\mathrm{HH},\mathrm{HT},\mathrm{TH},\mathrm{TT}\}$ とし、確率測度を $P(A) = \frac{|A|}4\quad\forall A\subseteq\Omega$ とする。
このとき、$A=\{\mathrm{HH},\mathrm{HT}\},\,B=\{\mathrm{HH},\mathrm{TH}\}$ とおくと、
\begin{align*}
P(A\cap B) &= \frac14,&P(A)&=P(B)=\frac12
\end{align*}
より $P(A\cap B) = P(A)P(B)$ を満たすことが分かる。
よって事象 $A,\,B$ は独立である。
:::

事象 $A$ と $B$ が独立であり、$P(B)>0$ であるとき、$P(A\mid B)=P(A)$ である。

## 確率変数の条件付き確率と独立性
事象は確率変数を通じて表すことが多い。そのため確率変数を用いた条件付き確率も定義する。

::: {#def-cond-rv}
### 確率変数
確率空間 $(\Omega,\,P)$ 上の確率変数 $X_1, X_2$ について同時確率を
\begin{align*}
\Pr(X_1\in A,\,X_2\in B) &\coloneqq P(\{\omega\in\Omega\mid X_1(\omega)\in A\}\cap\{\omega\in\Omega\mid X_2(\omega)\in B\}\})\quad\forall A,B\subseteq\mathbb{R}
\end{align*}
と定義する。確率変数が三つ以上の場合も同様に定義する。
また $\Pr(X_2\in B)>0$ のとき、条件付き確率は以下で定義する。
\begin{align*}
\Pr(X_1\in A\mid X_2\in B) &\coloneqq P(\{\omega\in\Omega\mid X_1(\omega)\in A\}\mid\{\omega\in\Omega\mid X_2(\omega)\in B\}\})\\
&=\frac{\Pr(X_1\in A, X_2\in B)}{\Pr(X_2\in B)}\qquad\forall A,B\subseteq\mathbb{R}.
\end{align*}
任意の $A,B\subseteq\mathbb{R}$ について、
\begin{align*}
\Pr(X_1\in A,\,X_2\in B)  &= \Pr(X_1\in A)\Pr(X_2\in B)
\end{align*}
を満たすとき、**確率変数 $X_1$ と $X_2$ は独立である**という。
:::

::: {#lem-ind-func}
確率空間 $(\Omega,\,P)$ 上の確率変数 $X_1, X_2$ が独立であるとする。
このとき任意の関数 $f_1,\,f_2\colon\mathbb{R}\to\mathbb{R}$ について、$f_1(X_1),\,f_2(X_2)$ は独立である。
:::
::: {.proof}
\begin{align*}
\Pr(f_1(X_1)\in A,\,f_2(X_2)\in B) &=
\Pr(X_1\in f_1^{-1}(A),\,X_2\in f_2^{-1}(B))\\
&=\Pr(X_1\in f_1^{-1}(A))\Pr(X_2\in f_2^{-1}(B))\\
&=\Pr(f_1(X_1)\in A)\Pr(f_2(X_2)\in B).
\end{align*}
:::

二つ以上の確率変数の累積分布関数を
\begin{align*}
F_{X_1,\dotsc,X_n}(x_1,\dotsc,x_n) &\coloneqq\Pr(X_1\le x_1,\dotsc,X_n\le x_n)
\end{align*}
と定義する。

## 離散型確率変数と確率質量関数

::: {#def-joint-mass}
確率空間 $(\Omega,\,P)$ 上の離散型確率変数 $X_1$, $X_2$ について、**同時確率質量関数**を
\begin{align*}
f_{X_1,\,X_2}(x_1,x_2) &\coloneqq \Pr(X_1=x_1,\,X_2=x_2)\\
\end{align*}
と定義する。
:::
同時確率質量関数からそれぞれの確率変数の確率質量関数が得られる。
\begin{align*}
f_{X_1}(x_1) &= \sum_{x_2} f_{X_1,\, X_2}(x_1, x_2)\\
f_{X_2}(x_2) &= \sum_{x_1} f_{X_1,\, X_2}(x_1, x_2)
\end{align*}
それぞれの確率変数の確率質量関数を**周辺質量関数**と呼ぶ。
同時確率質量関数から周辺質量関数を計算する操作のことを**周辺化**という。

::: {#def-joint-mass}
確率空間 $(\Omega,\,P)$ 上の離散型確率変数 $X_1$, $X_2$ について、**条件付き確率質量関数**を
\begin{align*}
f_{X_1\mid X_2}(x_1\mid x_2) &\coloneqq \Pr(X_1=x_1\mid X_2=x_2)
\end{align*}
と定義する。
:::
条件付き確率の定義より
\begin{align*}
f_{X_1,\,X_2}(x_1,x_2) &= f_{X_1\mid X_2}(x_1\mid x_2) f_{X_2}(x_2)
\end{align*}
が成り立つ。

::: {#lem-cond}
確率空間 $(\Omega,\,P)$ 上の**離散型**確率変数 $X_1, X_2$ について、
$X_1$ と $X_2$ が独立 $\iff$
\begin{align*}
f_{X_1,\,X_2}(x_1,x_2) &= f_{X_1}(x_1) f_{X_2}(x_2)
&\forall x_1\in\mathrm{Image}(X_1),x_2\in\mathrm{Image}(X_2).
\end{align*}
:::
::: {.proof}
$\Longrightarrow$ は自明。
$\Longleftarrow$ を示す。
\begin{align*}
\Pr(X_1\in A,\,X_2\in B)  &= \sum_{x_1\in A}\sum_{x_2\in B} \Pr(X_1=x_1,\,X_2=x_2)\\
&= \sum_{x_1\in A}\sum_{x_2\in B} \Pr(X_1=x_1)\Pr(X_2=x_2)\\
&= \Pr(X_1\in A)\Pr(X_2\in B)
\end{align*}
:::

::: {#exm-ind-rv}
### 二回のコイン投げ
標本空間を $\Omega = \{\mathrm{HH},\mathrm{HT},\mathrm{TH},\mathrm{TT}\}$ とし、確率測度を $P(A) = \frac{|A|}4\quad\forall A\subseteq\Omega$ とする。
\begin{align*}
X_1(\mathrm{HH})&=X_1(\mathrm{HT}) = 1,&
X_1(\mathrm{TH})&=X_1(\mathrm{TT}) = 0\\
X_2(\mathrm{HH})&=X_2(\mathrm{TH}) = 1,&
X_2(\mathrm{HT})&=X_2(\mathrm{TT}) = 0
\end{align*}
と定義する。
このとき、
\begin{align*}
f_{X_1,\,X_2}(x_1,\,x_2) &= \frac14\qquad\forall x_1,x_2\in\{0,1\}\\
f_{X_1}(x_1)=f_{X_2}(x_2)&=\frac12\qquad\forall x_1,x_2\in\{0,1\}
\end{align*}
より $f_{X_1,\,X_2}(x_1,\,x_2) = f_{X_1}(x_1)f_{X_2}(x_2)$ を満たすことが分かる。
よって確率変数 $X_1,\,X_2$ は独立である。
:::

## 連続型確率変数と確率密度関数
確率空間 $(\Omega,\,P)$ 上の連続型確率変数 $X_1$, $X_2$ について、**同時確率密度関数**を
\begin{align*}
%\Pr(\begin{bmatrix}X_1,\,X_2\end{bmatrix}\in A) &= \int_A f_{X_1,\,X_2}(x_1,x_2)\mathrm{d}x_1\mathrm{d}x_2
\Pr(X_1\in A,\,X_2\in B) &= \int_A\left(\int_B f_{X_1,\,X_2}(x_1,x_2)\mathrm{d}x_2\right)\mathrm{d}x_1
\end{align*}
を満たすものと定義する。
$X_1$ と $X_2$ が確率密度関数を持つ場合でも $X_1$ と $X_2$ の同時確率密度関数が存在するとは限らない。
例えば $X_1=X_2$ の場合がその例である。
逆に $X_1$ と $X_2$ が同時確率密度関数を持つとき、それぞれの確率密度関数は
\begin{align*}
f_{X_1}(x_1) &= \int_{-\infty}^\infty f_{X_1,\,X_2}(x_1,x_2)\mathrm{d}x_2\\
f_{X_2}(x_2) &= \int_{-\infty}^\infty f_{X_1,\,X_2}(x_1,x_2)\mathrm{d}x_1
\end{align*}
で得られる。この操作を確率密度関数の**周辺化**という。
同時確率密度関数を持つ確率変数 $X_1$, $X_2$ が独立であるとき、
\begin{align*}
f_{X_1,\,X_2}(x_1,x_2) &= f_{X_1}(x_1) f_{X_2}(x_2)
\end{align*}
が成り立つ。

## 三つ以上の独立確率変数
三つ以上の確率変数についても同時確率質量関数、同時確率密度関数を同様に定義する。
独立性についても同様に定義する。

::: {#def-ind-rvs}
確率空間 $(\Omega,\,P)$ 上の確率変数 $X_1, X_2,\dotsc, X_n$ が**独立** $\defiff$
\begin{align*}
\Pr(X_1\in A_1,\dotsc, X_n\in A_n) &= \prod_{k=1}^n \Pr(X_k\in A_k)\qquad\forall A_1,\dotsc,A_n\subseteq\mathbb{R}.
\end{align*}
:::

::: {#def-ind-rvs}
確率空間 $(\Omega,\,P)$ 上の確率変数 $X_1, X_2,\dotsc, X_n$ が**互いに独立** $\defiff$
任意の $1\le i< j\le n$ について、$X_i$ と $X_j$ が独立。
:::

確率変数 $X_1,\dotsc,X_n$ が独立であるとき、それらは互いに独立であることは以下から分かる。
\begin{align*}
\Pr(X_1\in A,\, X_2\in B) &= \Pr(X_1\in A,\, X_2\in B,\, X_3\in\mathbb{R},\dotsc, X_n\in\mathbb{R})\\
&= \Pr(X_1\in A)\Pr(X_2\in B) \prod_{k=3}^n \Pr(X_k\in\mathbb{R})\\
&= \Pr(X_1\in A)\Pr(X_2\in B).
\end{align*}

一方で確率変数 $X_1,\dotsc,X_n$ が互いに独立であっても、それらが独立であるとは限らない。
例えば、離散型確率変数 $X_1,\dotsc,X_n$ を
\begin{align*}
f_{X_1,\dotsc,X_n}(x_1,\dotsc,x_n)&=\begin{cases}
\frac1{2^{n-1}}&\text{if } \sum_{k=1}^n x_k \text{ is even}\\
0&\text{otherwise}
\end{cases}&
\forall x_1,\dotsc,x_n\in\{0,1\}
\end{align*}
と定義する。
このとき、確率変数 $X_n$ を周辺化すると
\begin{align*}
f_{X_1,\dotsc,X_{n-1}}(x_1,\dotsc,x_{n-1})&=
f_{X_1,\dotsc,X_n}(x_1,\dotsc,x_{n-1},0)+ f_{X_1,\dotsc,X_n}(x_1,\dotsc,x_{n-1},1)\\
&=\frac1{2^{n-1}}
\end{align*}
となる。つまり、$X_1,\dotsc,X_{n-1}$ は $\{0,1\}^{n-1}$ 上の一様分布に従う。
この確率分布は $X_1,\dotsc,X_n$ について対称なので、どの確率変数を周辺化しても一様分布に従う。
一様分布は独立なので、$n\ge 3$ のとき、どの二つの確率変数も独立である。

一方で、$n\ge 2$ のとき、これらの確率変数の周辺確率は一様である。つまり、
\begin{align*}
f_{X_k}(0) &= f_{X_k}(1) = \frac12\qquad\forall k=1,2,\dotsc,n.
\end{align*}
しかし、
\begin{align*}
f_{X_1,\dotsc,X_n}(x_1,\dotsc,x_n)&=\prod_{k=1}^n f_{X_k}(x_k)\qquad\forall x_1,\dotsc,x_n\in\{0,1\}
\end{align*}
は成り立たないので独立ではない。


## 独立な離散型確率変数の和

離散型確率変数 $X_1$ と $X_2$ が独立であるとする。
このとき、$X_1+X_2$ の確率質量関数は
\begin{align*}
f_{X_1+X_2}(x) &= \sum_z f_{X_1}(z)f_{X_2}(x-z)
\end{align*}
で与えられる。
これを確率質量関数の**畳み込み**という。

::: {#exm-binom}
二項分布の $N=1$ の場合をベルヌーイ分布 $\mathrm{Ber}(p)$ と呼ぶ。
つまり、$X\sim\mathrm{Ber}(p)\defiff$
\begin{align*}
\Pr(X=0) &= 1-p,& \Pr(X=1) &= p
\end{align*}
である。
確率変数 $X_1,X_2$ が独立で $\mathrm{Ber}(p)$ に従うとする。
このとき、$X_1+X_2$ は $\mathrm{Binom}(2, p)$ に従う。
\begin{align*}
\Pr(X_1+X_2 = 0) &= \Pr(X_1=0,\,X_2=0)\\
&= \Pr(X_1=0)\Pr(X_2=0) = (1-p)^2\\
\Pr(X_1+X_2 = 1) &= \Pr(X_1=0,\,X_2=1) + \Pr(X_1=1,\,X_2=0)\\
&=  \Pr(X_1=0)\Pr(X_2=1) + \Pr(X_1=1)\Pr(X_2=0)\\
&= 2p(1-p)\\
\Pr(X_1+X_2 = 2) &= \Pr(X_1=1,\,X_2=1)\\
&= \Pr(X_1=1)\Pr(X_2=1) = p^2
\end{align*}
と計算できる。
よって
\begin{align*}
\Pr(X_1+X_2 = k) &= \binom{2}{k} p^k(1-p)^{2-k}
\end{align*}
が成り立ち $X_1+X_2\sim\mathrm{Binom}(2, p)$ であることが分かる。
一般に、独立確率変数 $X_1,\,X_2$ について $X_1\sim\mathrm{Binom}(n, p)$, $X_2\sim\mathrm{Binom}(m, p)$ のとき、$X_1+X_2\sim\mathrm{Binom}(n+m,p)$ である。
\begin{align*}
\Pr(X_1+X_2 = k) &= \sum_{\ell\ge 0} \Pr(X_1 = \ell) \Pr(X_2 = k-\ell)\\
&= \sum_{\ell\ge 0} \binom{n}{\ell} p^\ell(1-p)^{n-\ell} \binom{m}{k-\ell} p^{k-\ell}(1-p)^{m-k+\ell}\\
&= \left(\sum_{\ell\ge 0} \binom{n}{\ell} \binom{m}{k-\ell}\right) p^k(1-p)^{n+m-k}\\
&= \binom{n+m}{k} p^k(1-p)^{n+m-k}.
\end{align*}

よって、$X_1,\dotsc,X_n$ が独立で $\mathrm{Ber}(p)$ に従うとき、$X_1+\dotsb+X_n$ は $\mathrm{Binom}(n, p)$ に従う。
:::
::: {#exm-poisson}
確率変数 $X_1$, $X_2$ が独立で $X_1\sim\mathrm{Poisson}(\lambda_1)$, $X_2\sim\mathrm{Poisson}(\lambda_2)$ とする。
このとき、
\begin{align*}
f_{X_1+X_2}(x) &= \sum_{z= 0}^x f_{X_1}(z) f_{X_2}(x-z)\\
&= \sum_{z= 0}^x \frac{\lambda_1^z}{z!}\mathrm{e}^{-\lambda_1}\frac{\lambda_2^{x-z}}{(x-z)!}\mathrm{e}^{-\lambda_2}\\
&= \frac1{x!}\mathrm{e}^{-(\lambda_1+\lambda_2)}\sum_{z=0}^x\binom{x}{z} \lambda_1^z\lambda_2^{x-z}\\
&= \frac1{x!}\mathrm{e}^{-(\lambda_1+\lambda_2)}(\lambda_1+\lambda_2)^x
\end{align*}
が成り立つ。よって $X_1+X_2\sim\mathrm{Poisson}(\lambda_1+\lambda_2)$ である。
独立なポアソン分布の和はポアソン分布に従う。
:::

これらの例のように、確率分布の族(集合)が畳み込みに閉じているとき、確率分布の族は**再生性**を持つという。
二項分布の場合はパラメータ $p$ を固定したときに再生性を持つ。

## 独立な連続型確率変数の和

連続確率変数 $X_1$ と $X_2$ が独立で密度関数を持つとき、
\begin{align*}
\Pr(X_1+X_2\in A) &= \int\int_{y+z\in A} f_{X_1}(y)f_{X_2}(z)\mathrm{d}y\mathrm{d}z\\
 &= \int\int_{x\in A} f_{X_1}(y)f_{X_2}(x-y)\mathrm{d}y\mathrm{d}x \qquad(x=y+z)\\
 &= \int_{A} \left(\int_{-\infty}^\infty f_{X_1}(y)f_{X_2}(x-y)\mathrm{d}y\right)\mathrm{d}x \qquad(x=y+z)\\
\end{align*}
と表せるので、$X_1+X_2$ は確率密度関数を持ち
\begin{align*}
f_{X_1+X_2}(x) &= \int_{-\infty}^\infty f_{X_1}(z)f_{X_2}(x-z)\mathrm{d} z
\end{align*}
とすることができる。
確率変数 $X_1,\,X_2$ が独立で $X_1\sim N(\mu_1,\,\sigma_1^2)$, $X_2\sim N(\mu_2,\,\sigma_2^2)$ とする。
このとき、
\begin{align*}
f_{X_1+X_2}(x) &= \int_{-\infty}^\infty f_{X_1}(z)f_{X_2}(x-z)\mathrm{d} z\\
 &= \int_{-\infty}^\infty \frac1{\sqrt{2\pi\sigma_1^2}} \mathrm{e}^{-\frac{(z-\mu_1)^2}{2\sigma_1^2}}\frac1{\sqrt{2\pi\sigma_2^2}} \mathrm{e}^{-\frac{(x-z-\mu_2)^2}{2\sigma_2^2}}\mathrm{d} z\\
 &= \frac1{2\pi\sqrt{\sigma_1^2\sigma_2^2}}\int_{-\infty}^\infty  \mathrm{e}^{-\frac{\sigma_2^2(z-\mu_1)^2+\sigma_1^2(x-z-\mu_2)^2}{2\sigma_1^2\sigma_2^2}}\mathrm{d} z\\
 &= \frac1{2\pi\sqrt{\sigma_1^2\sigma_2^2}}\int_{-\infty}^\infty  \mathrm{e}^{-\frac{(\sigma_1^2+\sigma_2^2)\left(z-\frac{\sigma_2^2\mu_1+\sigma_1^2(x-\mu_2)}{\sigma_1^2+\sigma_2^2}\right)^2 + \sigma_2^2\mu_1^2 + \sigma_1^2(x-\mu_2)^2 - \frac{(\sigma_2^2\mu_1+\sigma_1^2(x-\mu_2))^2}{\sigma_1^2+\sigma_2^2}}{2\sigma_1^2\sigma_2^2}}\mathrm{d} z\\
 &= \frac1{\sqrt{2\pi(\sigma_1^2+\sigma_2^2)}}\mathrm{e}^{-\frac{\sigma_2^2\mu_1^2 + \sigma_1^2(x-\mu_2)^2 - \frac{(\sigma_2^2\mu_1+\sigma_1^2(x-\mu_2))^2}{\sigma_1^2+\sigma_2^2}}{2\sigma_1^2\sigma_2^2}}\\
 &= \frac1{\sqrt{2\pi(\sigma_1^2+\sigma_2^2)}}\mathrm{e}^{-\frac{(x-(\mu_1+\mu_2))^2}{2(\sigma_1^2+\sigma_2^2)}}\\
\end{align*}
が成り立つので $X_1+X_2\sim N(\mu_1+\mu_2,\,\sigma_1^2+\sigma_2^2)$ であることが分かる。
よって正規分布は再生性を持つ。

<!--
## 多変量確率変数の例

$\mathrm{Pos}(n)$ を $n\times n$ の正定値対称行列の集合とする。
$\mathbf{\mu}\in\mathbb{R}^n$ と $\Sigma\in \mathrm{Pos}(n)$ について、多変量正規分布 $N(\mathbf{\mu},\,\Sigma)$ は以下の確率密度関数を持つ。
-->
