# 確率空間

## 確率論を数学的に定式化するには

確率は身近に現れる(感じられる)ものであるが、それを数学的に定式化することは自明な問題ではない。
実際に確率論には複数の数学的定式化が存在する。
その中で圧倒的に一般的なのが**測度論的確率論**と呼ばれる定式化である。
測度というのは集合の「面積」のようなものであり、確率を測度と捉えるのが測度論的確率論である。
これは多くの人間の直感にも自然なものであろう。

まず、確率を考える集合について考えよう。
例えばコインを投げて表もしくは裏が出る確率を考えたいときは
$$
\Omega = \{\mathrm{H},\,\mathrm{T}\}
$$
という集合になる。
また、明日の天気の確率を考えたいときは
$$
\Omega = \{\text{"晴"},\, \text{"雨"},\, \text{"雪"}\}
$$
という集合になるだろう。
この $\Omega$ の部分集合に確率を与える関数 $P\colon 2^\Omega\to\mathbb{R}$ を定義しよう。
偏りのないコインの場合は以下のようになる。
\begin{align*}
P(\varnothing) &= 0,& P(\{\mathrm{H}\}) &= \frac12,&
P(\{\mathrm{T}\}) &= \frac12,& P(\{\mathrm{H},\,\mathrm{T}\}) &= 1.
\end{align*}
また、天気の場合は例えば以下のようになる。
\begin{align*}
P(\varnothing)&=0,& P(\{晴\})&=0.7,& P(\{雨\})&=0.2,& P(\{雪\})&=0.1\\
P(\{晴,雨\})&=0.9,& P(\{雨,雪\})&=0.3,& P(\{雪,晴\})&=0.8,&P(\{晴,雨,雪\})&=1.
\end{align*}

このように集合 $\Omega$ の部分集合に確率を与えることを考える。
$\Omega$ の要素一つずつに確率を与えれば十分であるようにも思えるが、$\Omega$ が連続的な場合には $\Omega$ の一つの要素の確率は 0 になってしまうことが多い。
例えば明日の正午の気温が $10\pi \,{}^\circ\mathrm{C}$ になる確率は 0 であろう。
そのため、$\Omega$ の要素ではなく部分集合に確率を与えることにする。
そのために測度論が適しているわけである。


## 有限集合上の確率空間

確率を考える集合を $\Omega$ とする。
この $\Omega$ のことを**標本空間**という。
また、$\Omega$ の部分集合のことを**事象**という。
そして、事象に確率を与える関数 $P\colon 2^\Omega\to\mathbb{R}_{\ge 0}$ を**確率測度**という。
確率測度は以下の条件を満たす。

1. $P(\Omega)=1$.
2. $\forall A,\,B\subseteq\Omega,\quad A\cap B = \varnothing \implies P(A\cup B) = P(A) + P(B)$.

一つ目の条件は全体の確率が1であるという意味の条件である。
二つ目の条件は排反な二つの事象の和集合の確率はそれぞれの事象の確率の和であるという意味の条件である。
この二つ目の条件を**有限加法性**という。
例えば
$$
P(\{\text{"晴"}, \text{"雨"}\}) = P(\{\text{"晴"}\}) + P(\{\text{"雨"}\})
$$
という等式は「晴れもしくは雨になる確率 $=$ 晴れになる確率 $+$ 雨になる確率」という意味の等式になる。
よって有限加法性が自然な条件であることが分かるだろう。
また、これらのことから、$P$ は各要素 $\omega\in\Omega$ に対する確率 $P(\{\omega\})$ から一意に定まることが分かる。
この標本空間と確率測度のペア $(\Omega,\, P)$ を**確率空間**という。

## 可算無限集合上の確率

標本空間 $\Omega$ が可算無限集合のときも、同様に確率測度を定義することもできるが、ここではより強い以下の条件を考える。

1. $P(\Omega)=1$.
2. $\forall (A_n\subseteq \Omega)_{n\ge 0},\quad \forall i\ne j,\, A_i\cap A_j=\varnothing\implies P\left(\bigcup_{n\ge 0}A_n\right) = \sum_{n\ge 0} P(A_n)$.

この二つ目の条件を**完全加法性**もしくは **$\sigma$-加法性**という。
ここで
$$
\bigcup_{n\ge 0} A_n = \{\omega\in\Omega\mid \exists n\ge 0,\, \omega\in A_n\}
$$
は事象列 $(A_n)_{n\ge 0}$ の並び順に依存しない。
よって、$P$ の完全加法性が成り立つとき
$$
\sum_{n\ge 0} P(A_n)
$$
も事象列 $(A_n)_{n\ge 0}$ の並び順に依存しない。
そもそも $P(A_n)\ge 0$ なので、無限和 $\sum_{n\ge 0} P(A_n)$ が存在するときこれは絶対収束することから、この無限和は事象列の並び順に依存しないことが分かる。
完全加法性ではなく有限加法性だけを使って確率論を構築する試みもあるが、確率測度の連続性などの性質が失なわれるため
標準的な確率論では完全加法性を課す。

## すべての部分集合を可測にはできない

より一般に $\Omega$ が非可算無限集合の場合を考えよう。例えば $\Omega = [0, 1)$ の場合が考えられる。
このとき、すべての $A\subseteq\Omega$ に確率を与えることができるのだろうか？
そうすると、ごく自然な性質を持つような確率測度が存在しないことが、選択公理を認めると示される。

::: {#thm-vitali}

## 非可測集合の存在

$\Omega=[0,1)$ とする。
また、集合の平行移動を
$$
A+x\coloneqq\{a+x-\lfloor a+x\rfloor\mid a\in A\}
$$
と定義する。
このとき、
$$
\forall x\in\Omega,\, A\subseteq\Omega,\quad P(A+x) = P(A)\qquad\text{平行移動不変性}
$$
を満たす確率測度 $P\colon 2^{[0,1)}\to \mathbb{R}_{\ge 0}$ は存在しない。

:::
::: {.proof}
$\Omega$ 上の同値関係を $x\sim y \stackrel{\mathrm{def}}{\iff} x-y\in\mathbb{Q}$ と定義する。
選択公理より、この同値関係の同値類から一つずつ要素を含む集合 $V$ が存在する(Vitali集合)。
任意の $x\in[0, 1)$ について、ある $z\in V$ が**唯一**存在して $x\sim z$ である。
よって、任意の $x\in[0, 1)$ について、ある $z\in V$ と $q\in\mathbb{Q}$ が**唯一**存在して $x = z+q$ であることから
\begin{align*}
[0, 1) &= \bigcup_{q\in\mathbb{Q}} (V + q)
\end{align*}
であり、右辺は互いに排反である。
よって条件を満たす $P$ が存在すると仮定すると、
\begin{align*}
1 = P([0, 1)) &= P\left(\bigcup_{q\in\mathbb{Q}} (V+q)\right)\\
 &= \sum_{q\in\mathbb{Q}} P\left(V+q\right)\qquad \text{(完全加法性)}\\
 &= \sum_{q\in\mathbb{Q}} P\left(V\right)\qquad \text{(平行移動不変性)}
\end{align*}
ここで $P(V)$ をどのように定めても、それを無限回足して 1 にすることはできない。
よって $P$ は存在しない。
:::

## 確率論の公理

@thm-vitali より、

1. 選択公理
2. 確率測度の完全加法性
3. $[0, 1)$ 上の平行移動不変な確率測度
4. $\Omega$ のすべての部分集合に確率を与える

のどれかを諦めないといけない。
標準的な確率論では4を諦める。
以下に確率空間の厳密な定義を述べる。

::: {#def-sigma}

## 完全加法族

$\Omega$ を集合とする。
$\mathcal{F}\subseteq 2^\Omega$ が以下を満たすとする。

1. $\Omega\in\mathcal{F}$.
2. $\forall A\in\mathcal{F},\quad \Omega\setminus A\in\mathcal{F}$.
3. $\forall (A_n\in\mathcal{F})_{n\ge 0},\quad \bigcup_{n\ge 0} A_n\in\mathcal{F}$.

このとき、$\mathcal{F}$ を $\Omega$ 上の完全加法族もしくは $\sigma$-加法族という。
:::

::: {#def-prob}

## 確率空間

$\Omega$ を集合とし、
$\mathcal{F}\subseteq 2^\Omega$ を $\Omega$ 上の完全加法族とする。

また、$P\colon\mathcal{F}\to\mathbb{R}_{\ge 0}$ が以下を満たすとする。

1. $P(\Omega)=1$.
2. $\forall (A_n\in \mathcal{F})_{n\ge 0},\quad \forall i\ne j,\, A_i\cap A_j=\varnothing\implies P\left(\bigcup_{n\ge 0}A_n\right) = \sum_{n\ge 0} P(A_n)$.

このとき、$(\Omega,\, \mathcal{F},\, P)$ を確率空間という。
また、$\Omega$ を標本空間、$\mathcal{F}$ を事象集合、$P$ を確率測度という。
:::

このように事象集合 $\mathcal{F}$ の元についてのみ確率が与えられる。

::: {.callout-note}
ペア $(\Omega,\, \mathcal{F})$ を可測空間という。
確率空間 $(\Omega,\, \mathcal{F},\, P)$ から $P(\Omega)=1$ の条件を除いたものが一般の測度空間である。
:::


@thm-vitali の証明では選択公理を用いたが、実際に選択公理を認めないと @thm-vitali が成立しないことが分かっている。
以降、$\Omega$ が非可算無限集合である場合も含めて、$\mathcal{F} = 2^\Omega$ だと思うことにする。
これは正しくない場合もあるのだが、選択公理を使わない限り矛盾は導かれないので、問題になることはほとんどない。

よって、以降は $(\Omega,\, P)$ を確率空間とする。
