[project]
name = "prob-stat-book"
version = "0.1.0"
description = "Add your description here"
requires-python = "~= 3.13.0"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "scipy>=1.15.2",
]
