# 集合論

## 集合

集合は対象の集まりである。例えば

\begin{align*}
A&=\{1,2,3\},& B&=\{赤,青,黄,緑\}
\end{align*}

のように表す。

* $x\in A$ で要素 $x$ は集合 $A$ に含まれる
* $x\notin A$ で要素 $x$ は集合 $A$ に含まれない

を表す。

$|A|$ で集合 $A$ の要素数を表すことにする。
要素数が無限の集合を考えることもできる。
例えば

\begin{align*}
A&=\{n\in\mathbb{N}\mid \text{$n$ は偶数}\},& B&=\{x\in\mathbb{R}\mid \text{$x$ は無理数} \}
\end{align*}

という集合は無限集合の例となる。
何も要素を持たない集合(要素数が零の集合)を**空集合**といい、$\varnothing$ で表す。

## 集合の関係

集合 $A$ の要素がすべて集合 $B$ に含まれるとき、$A$ を $B$ の**部分集合** という。
部分集合に関連する集合関係について記号を以下のように定義する。

\begin{align*}
A\subseteq B &\defiff (x\in A\implies x \in B)&\text{($A$ は $B$ の部分集合)}\\
A\supseteq B &\defiff B\subseteq A&\text{($A$ は $B$ の上位集合)}\\
A = B &\defiff (A\subseteq B\land A\supseteq B)& \text{($A$ と $B$ は等しい)}\\
A \ne B &\defiff \lnot(A = B)& \text{($A$ と $B$ は等しくない)}
\end{align*}

また、

\begin{align*}
A\subsetneq B &\defiff (A\subseteq B \land A\ne B)&\text{($A$ は $B$ の真部分集合)}\\
A\supsetneq B &\defiff B\subsetneq A&\text{($A$ は $B$ の真上位集合)}
\end{align*}

とする。
部分集合や上位集合のような集合間の関係を**包含関係**という。
集合 $A,\,B$ について、$A\subseteq B$ と $B\subseteq A$ のどちらかが成り立つとき、「$A$ と $B$ の間に包含関係が成り立つ」という。

包含関係は以下の三条件を満たす。

* (反射律) $\quad A\subseteq A$.
* (反対称律) $\quad (A\subseteq B\land B\subseteq A) \iff A = B$.
* (推移律) $\quad (A\subseteq B\land B\subseteq C)\implies A\subseteq C$.

## 集合の演算

複数の集合から新しい集合を作る演算がある。

\begin{align*}
A\cup B &\coloneqq\left\{x\mid x\in A \text{ または } x \in B\right\}\qquad\text{(和集合)}\\
A\cap B &\coloneqq \left\{x\mid x\in A \text{ かつ } x \in B\right\}\qquad\text{(積集合)}\\
A\setminus B &\coloneqq \left\{x\mid x\in A \text{ かつ } x \notin B\right\}\qquad\text{(差集合)}
\end{align*}

また、全体の集合 $\Omega$ というのが文脈上存在する場合は、

\begin{align*}
A^\mathrm{c} &\coloneqq \Omega\setminus A\qquad\text{(補集合)}
\end{align*}

と定義する。
これらの演算は以下の法則を満たす。

* (交換法則) $\quad A\cup B = B\cup A, \quad A\cap B = B\cap A$.
* (結合法則) $\quad (A\cup B)\cup C = A\cup (B\cup C), \quad (A\cap B)\cap C=A\cap(B\cap C)$.
* (分配法則) $\quad A\cup(B\cap C) = (A\cup B)\cap (A\cup C),\quad A\cap (B\cup C) = (A\cap B)\cup (A\cap C)$.
* (冪等法則) $\quad A \cup A = A, \quad A\cap A = A$.
* (吸収法則) $\quad A \cup (A\cap B) = A, \quad A\cap (A\cup B) = A$.
* $A\cup \varnothing = A,\quad A\cap\varnothing = \varnothing$.

補集合に関連して以下の法則を満たす。

* $A\cup \Omega = \Omega,\quad A\cap\Omega = A$.
* $A\cup A^\mathrm{c} = \Omega,\quad A\cap A^\mathrm{c} =\varnothing$.
* (ド・モルガンの法則) $\quad(A\cup B)^\mathrm{c} = A^\mathrm{c} \cap B^\mathrm{c},\quad(A\cap B)^\mathrm{c} = A^\mathrm{c} \cup B^\mathrm{c}$
* (二重補集合の法則) $\quad (A^\mathrm{c})^\mathrm{c} = A$.
* $\Omega^\mathrm{c} = \varnothing,\quad \varnothing^\mathrm{c} = \Omega$.

和集合と積集合は結合法則満たすことから、括弧を使わずに $A\cup B\cup C$ と表すことができる。

## 集合族

集合 $\Omega$ について $2^\Omega$ を $\Omega$ の部分集合からなる集合を表す。

\begin{align*}
2^\Omega &\coloneqq \left\{A\subseteq\Omega\right\}.
\end{align*}

このような集合を要素に持つ集合を**集合族**と呼ぶ。
例えば $\Omega=\{1,2,3\}$ のとき、

$$
2^\Omega = \left\{\varnothing, \{1\}, \{2\}, \{3\}, \{1,2\},\{2,3\},\{1,3\},\{1,2,3\}\right\}
$$

である。
集合 $\Lambda$ の各 $\lambda\in\Lambda$ に対して集合 $A_\lambda\subseteq\Omega$ が存在するとき、集合族

$$
\left\{A_\lambda\subseteq\Omega\mid \lambda\in\Lambda\right\}\subseteq 2^\Omega
$$

を**添字集合 $\Lambda$ で添字付けられた $\Omega$ 上の集合族**という。
添字集合が有限集合の場合は和集合や積集合は二つの集合の和集合と積集合の定義を繰り返し用いることで定義できる。
それらは以下のように表す。

$$
\bigcup_{\lambda\in\Lambda} A_\lambda \quad,\quad
\bigcap_{\lambda\in\Lambda} A_\lambda
$$

添字集合 $\Lambda$ が無限集合の場合は和集合と積集合を以下で定義する。

\begin{align*}
\bigcup_{\lambda\in\Lambda} A_\lambda
&\coloneqq
\left\{x\in\Omega\mid \exists \lambda\in\Lambda,\quad x\in A_\lambda\right\}\\
\bigcap_{\lambda\in\Lambda} A_\lambda
&\coloneqq
\left\{x\in\Omega\mid \forall \lambda\in\Lambda,\quad x\in A_\lambda\right\}
\end{align*}

この場合もド・モルガンの法則は成り立つ。つまり、

\begin{align*}
\left(\bigcup_{\lambda\in\Lambda} A_\lambda\right)^\mathrm{c}
&=
\bigcap_{\lambda\in\Lambda} A_\lambda^\mathrm{c}\\
\left(\bigcap_{\lambda\in\Lambda} A_\lambda\right)^\mathrm{c}
&=
\bigcup_{\lambda\in\Lambda} A_\lambda^\mathrm{c}
\end{align*}

が成り立つ。

証明:
$x\in\Omega$ について、
\begin{align*}
x\in\left(\bigcup_{\lambda\in\Lambda} A_\lambda\right)^\mathrm{c}
&\iff x\notin\left(\bigcup_{\lambda\in\Lambda} A_\lambda\right)\\
&\iff \lnot\left(\exists\lambda\in\Lambda,\quad x\in A_\lambda\right)\\
&\iff \forall\lambda\in\Lambda,\quad x\notin A_\lambda\\
&\iff \forall\lambda\in\Lambda,\quad x\in A_\lambda^\mathrm{c}\\
&\iff x\in\bigcap_{\lambda\in\Lambda} A_\lambda^{\mathrm{c}}.
\end{align*}
