# 定常分布
## 遷移グラフ
マルコフ連鎖の推移行列 $T$ について、
\begin{align*}
\mu T &= \mu
\end{align*}
を満たす確率ベクトル(非負で成分の和が1) $\mu$ を定常分布と呼ぶのであった。
定常分布の存在、唯一性、極限分布との一致について考える。
参考文献 [@levin2017markov]。

:::{#def-digraph}
### 有向グラフ
有限集合 $V$ と集合 $E\subseteq V\times V$ のペア $G=(V,\,E)$ を有向グラフという。
$V$ の元を**頂点**、$E$ の元を**辺(有向辺)**と呼ぶ。
:::

有向辺 $(u,v)\in E$ は頂点 $u$ から頂点 $v$ への有向辺と解釈することにする。

:::{#def-trgraph}
### 遷移グラフ
有向グラフ $G=(V,\,E)$ が状態集合 $S$ 上のマルコフ連鎖の遷移行列 $T$ の**遷移グラフ** $\defiff$
\begin{align*}
V&= S\\
E&=\left\{(u,v)\in V\times V\mid T_{u,v}>0\right\}.
\end{align*}
:::

マルコフ連鎖の定常分布や収束に関する議論をする際には遷移確率は 0 か正かということが問題になり、具体的な値は問題にならない。
したがって、定常分布が唯一であるための条件などは遷移グラフの性質として表すことができる。

## 既約性と定常分布

:::{#def-cycle}
### 有向グラフのウォーク
有向グラフ $G=(V,E)$ の頂点列
\begin{align*}
(v_0,v_1,\dotsc,v_\ell)
\end{align*}
で各 $i=0,1,\dotsc,\ell-1$ について $(v_i,\,v_{i+1})\in E$ を満たすものを**($v_0$ から $v_{\ell}$ への)ウォーク**という。
また、$\ell$ をウォークの**長さ**という。
:::

頂点列 $(v)$ は長さ0のウォークであることに気をつけよう。
遷移グラフの定義より、任意の $u,v\in S$ について
\begin{align*}
&\text{遷移グラフ上に $u$ から $v$ への長さ $\ell$ のウォークが存在する} \iff (T^\ell)_{u,v} > 0\\
\iff&\Pr(X_\ell=v\mid X_0=u) > 0
\end{align*}
である。



:::{#def-equiv}
### 順序関係
推移行列 $T$ を持つマルコフ連鎖の状態 $u,v\in S$ について $u\le_T v$ $\defiff$ その遷移グラフにおいて $u$ から $v$ へのウォークが存在する。
また、$u\le_T v$ かつ $v\le_T u$ のとき、$u\sim_T v$ とする。
:::

この $\le_T$ は以下の前順序関係の公理を満たす。

* (反射律) $\forall u\in S,\, u\le_T u$.
* (推移律) $\forall u,v,w\in S,\, (u\le_T v\,\land\, v\le_T w) \implies u\le_T w$.

また、$\sim_T$ は以下の同値関係の公理を満たす。

* (反射律) $\forall u\in S,\, u\sim_T u$.
* (対称律) $\forall u,v\in S,\, u\sim_T v\implies v\sim_T u$.
* (推移律) $\forall u,v,w\in S,\, (u\sim_T v\,\land\, v\sim_T w) \implies u\sim_T w$.


::: {#def-irred}
### マルコフ連鎖の既約性

マルコフ連鎖が**既約**である $\defiff$
任意の $u,v\in S$ について $u\sim_T v$.
<!--
任意の $x,y\in S$ についてある $t\in\mathbb{Z}_{\ge 0}$ が存在して、
\begin{align*}
\Pr(X_t=y\mid X_0 = x)&>0
\end{align*}
$\iff$
任意の $x,y\in S$ についてある $t\in\mathbb{Z}_{\ge 0}$ が存在して、$(T^t)_{x,y}>0$.
-->
:::

有向グラフ $G$ の任意の頂点 $u, v\in V$ について $u$ から $v$ へのウォークが存在するとき、$G$ は**強連結**であるという。
よってマルコフ連鎖が既約 $\iff$ 遷移グラフが強連結である。

```{dot}
//| fig-width: 7
//| fig-height: 3
//| fig-cap: 既約なマルコフ連鎖の遷移グラフ。任意の頂点 $u, v\in V$ について、$u$ から $v$ へのウォークが存在する。
digraph irreduc_graph {
  graph [rankdir=LR];
  node [shape=circle, width=0.1, fontsize=20];

  1 -> 2;
  2 -> 3;
  3 -> 1;

  3 -> 4;
  4 -> 2;
  2 -> 5;
  5 -> 1;
  4 -> 4;
}
```


::: {#lem-irred}
既約なマルコフ連鎖について $\mathrm{Ker}(I-T)=\mathrm{span}(1)$ である。
:::
::: {.proof}
列ベクトル $v\in\mathbb{R}^n$ を
\begin{align*}
(I-T)v = 0 &\iff Tv = v
\end{align*}
を満たすものとする。
このとき、$i\in\arg\max_{k\in S} v_k$ とすると
\begin{align*}
v_i &= \sum_{j\in S} T_{i,j} v_j\\
&= \sum_{j\in S\colon\,(i,j)\in E} T_{i,j} v_j\\
&\le \sum_{j\in S\colon\,(i,j)\in E} T_{i,j} v_i\\
&= v_i
\end{align*}
という不等式が得られる。
この不等号は等号でなくてはいけないので、
\begin{align*}
v_j &= v_i\qquad\text{if } (i, j)\in E
\end{align*}
である。
この議論を繰り返すと $i\le_T j$ である $j$ について $v_j=v_i$ である。
マルコフ連鎖が既約であることから、任意の $j\in S$ について $i\le j$ であり、$v = v_i 1$ である。
したがって、$\mathrm{Ker}(I-T)=\mathrm{span}(1)$ である。
:::

よって既約なマルコフ連鎖に対して定常分布は高々一つである。
実際には既約なマルコフ連鎖は一つの定常分布を持つ。

:::{.callout-note}
### 証明の方針
既約なマルコフ連鎖が定常分布を持つことの証明には大きく分類して3通りの方法がある。

1. ブラウワーの不動点定理。
1. 確率論的な議論(再帰時間)で明示的に定常状態を与える。定常状態は直感的に記述できる。
1. 線形代数的な議論(マルコフ連鎖木定理)で組合せ的な記述で明示的に定常状態を与える。

以下では3番目の方針に従い、明示的な定常状態は与えず、その存在だけを示す。
:::

::: {#thm-irred}
既約なマルコフ連鎖は唯一の定常分布 $\mu\in\mathbb{R}_{>0}^n$ を持つ。
:::
:::{.proof}
マルコフ連鎖の**ラプラシアン行列**を $\Lambda \coloneqq I-T$ と定義する。
ラプラシアン行列の余因子行列を $\mathrm{adj}(\Lambda)$ で表す($\mathrm{adj}(\Lambda)$ の $(i,j)$ 成分は $(j,i)$ 余因子である)。
余因子展開より
\begin{align*}
\mathrm{adj}(\Lambda)\Lambda &= \Lambda\,\mathrm{adj}(\Lambda) = \det(\Lambda)I
\end{align*}
である。確率行列 $T$ は固有値1を持つので、$\det(\Lambda)=0$ である。
よって、
\begin{align*}
\mathrm{adj}(\Lambda)\Lambda &= \Lambda\,\mathrm{adj}(\Lambda) = O
\end{align*}
である。
まず、$\Lambda\,\mathrm{adj}(\Lambda)=O$ と @lem-irred より $\mathrm{adj}(\Lambda)$ の各列は $1$ のスカラー倍である。よって、$\mathrm{adj}(\Lambda)$ の行はすべて等しい。
次に、$\mathrm{adj}(\Lambda)\Lambda=O$ より、$\mathrm{adj}(\Lambda)$ の行 $\mu\in\mathbb{R}^n$ は $\mu\Lambda=0$ を満たす。
ここで、$\mathrm{adj}(\Lambda)$ の行がすべて等しいことから
\begin{align*}
\mu_i &= \mathrm{adj}(\Lambda)_{i,i}\qquad\forall i\in S
\end{align*}
が成り立つ。
よって
\begin{align*}
\mathrm{adj}(\Lambda)_{i,i}&>0\qquad\forall i\in S
\end{align*}
を示せば十分である。
余因子行列の定義より、
\begin{align*}
\mathrm{adj}(\Lambda)_{i,i}&= \det(I - T^{(i)})
\end{align*}
である。
ここで、$T^{(i)}$ は $T$ の $i$ 行目と $i$ 列目を削除して得られる行列である。

目標である $\det(I-T^{(i)})>0$ を示すためには $\rho(T^{(i)})<1$ を示せば十分である。

:::{.callout-note}
### $\rho(A)<1\implies \det(I-A)>0$ の代数的な証明
実正方行列 $A$ の固有値の多重集合を $\mathrm{spec}(A)$ で表すことにする。
実多項式の実数でない根はその複素共役とペアで現れることに注意すると、
\begin{align*}
\det(I-A)&= \prod_{\lambda\in\mathrm{spec}(A)} (1-\lambda)\\
&= \prod_{\lambda\in\mathrm{spec}(A)\cap\mathbb{R}} (1-\lambda)
\cdot \prod_{\lambda\in\mathrm{spec}(A)\setminus\mathbb{R}} (1-\lambda)\\
&= \prod_{\lambda\in\mathrm{spec}(A)\cap\mathbb{R}} (1-\lambda)
\cdot \prod_{\lambda\in\mathrm{spec}(A)\setminus\mathbb{R}} |1-\lambda|\\
\end{align*}
よって $\rho(A)<1$ であれば $\det(I-A)>0$ である。
:::


:::{.callout-note}
### $\rho(A)<1\implies \det(I-A)>0$ の解析的な証明
実正方行列 $A$ の特性多項式を
\begin{align*}
p_A(x) &\coloneqq \det(xI - A)
\end{align*}
と定義する。
これはモニックな多項式であるため $x\to+\infty$ で $p_A(x)\to+\infty$ である。
よって $p_A(x)$ が実根を持たないもしくは、すべての実根が 1 未満であれば $p_A(1)>0$ である。
特性多項式 $p_A$ の根は $A$ の固有値なので、$\rho(A)<1$ であれば $p_A(1)=\det(I-A)>0$ である。
:::

よって、$\rho(T^{(i)})<1$ を示せば $\mathrm{adj}(\Lambda)_{i,i}=\det(I-T^{(i)}) > 0$ がしたがう。

<!--
任意の $k\in\mathbb{Z}_{\ge 0}$ について、
\begin{align*}
\rho(T^{(i)k}) &= \rho(T^{(i)})^k
\end{align*}
より、
\begin{align*}
\rho(T^{(i)k}) < 1 &\iff \rho(T^{(i)}) < 1
\end{align*}
である。
-->
$T^{(i)}$ の絶対値最大の固有値を $\lambda$ とおき、対応する固有ベクトルを $v$ とする。
このとき
\begin{align*}
T^{(i)}v &= \lambda v
\end{align*}
が成り立つ。
$v$ の絶対値最大の成分のインデックスを $j\in S\setminus\{i\}$ とおく。
マルコフ連鎖が既約であることから、その遷移グラフ上で $j$ から $i$ へのウォークが存在する。
そのウォークの長さを $\ell\in\mathbb{Z}_{\ge 1}$ とおく。
このとき、$S\coloneqq T^{(i)\ell}$ とおくと、
\begin{align*}
S v &= \lambda^\ell v
\end{align*}
である。
ここで、$S$ の $j$ 行目の和は
\begin{align*}
\sum_k S_{j,k} &= \Pr(X_1\ne i,\dotsc,X_\ell \ne i\mid X_0 = j) < 1
\end{align*}
である。
よって、
\begin{align*}
|\lambda^\ell v_j| &= |(S v)_j|\\
&= \left|\sum_{k}S_{j,k} v_k\right|\\
&\le \sum_{k}S_{j,k} \left|v_k\right|\\
&\le \sum_{k}S_{j,k} |v_j|\\
&< |v_j|\\
\end{align*}
である。$|v_j|>0$ より、$|\lambda|<1$ である。
したがって、$\rho(T^{(i)}) < 1$ であることが示された。
:::

## 一般のマルコフ連鎖の定常分布

次に既約とは限らない一般のマルコフ連鎖について考える。
マルコフ連鎖の状態集合 $S$ を同値関係 $\sim_T$ で割った同値類 $S/\sim_T$ を考える。
そして、その同値類の遷移グラフを考える。

:::{#def-digraph-equiv}
### 同値類の遷移グラフ
有向グラフ $G=(V,\,E)$ が状態集合 $S$ 上のマルコフ連鎖の遷移行列 $T$ の**遷移グラフ** $\defiff$
\begin{align*}
V&= S/\sim_T\\
E&=\left\{(u,v)\in V\times V\mid \exists u\in U, v\in V\quad T_{u,v}>0\right\}.
\end{align*}
:::

マルコフ連鎖の遷移グラフから同値類の遷移グラフは定まる。

:::{#def-digraph-scc}
### 強連結成分と縮約グラフ

有向グラフ $G=(V,E)$ について、$V$ 上の同値関係を $u\sim v\defiff \text{$u$ と $v$ の間に両方向のパスがある}$と定義する。
この同値関係の同値類を $G$ の**強連結成分**と呼ぶ。

$G$ の強連結成分を頂点に持つ**縮約グラフ** $G'=(V',E')$ を
\begin{align*}
V'&=V/\sim\\
E'&=\left\{(A,B)\in V'\times V'\mid \exists a\in A, \exists b\in B, (a,b)\in E, A\ne B\right\}
\end{align*}
と定義する。
:::

```{dot}
//| fig-width: 7
//| fig-height: 3
//| fig-cap: 有向グラフの例。強連結ではない。
digraph tgraph {
  graph [rankdir=LR];
  node [shape=circle, width=0.1, fontsize=20];

  1 -> 2;
  2 -> 3;
  3 -> 1;

  2 -> 4;
  2 -> 5;
  5 -> 6;
  6 -> 5;
  4 -> 7;
  6 -> 7;
  1 -> 7;
  7 -> 7;
}
```
```{dot}
//| fig-width: 7
//| fig-height: 3
//| fig-cap: 上の図の有向グラフの縮約グラフ。
digraph tgraph_equiv {
  rankdir=LR;
  node [shape=circle, width=0.6, margin="0.01", fixedsize=true, fontsize=10];

  a [label="{1, 2, 3}"]
  b [label="{4}"]
  c [label="{5, 6}"]
  d [label="{7}"]

  a -> b;
  a -> d;
  a -> c;
  b -> d;
  c -> d;
}
```


:::{#def-dag}
### 有向非巡回グラフ
有向グラフ $G$ の長さ1以上のウォーク $(v_0,\dotsc,v_\ell)$ が

1. $v_\ell=v_0$.
1. $v_0,\dotsc,v_{\ell-1}$ がすべて異なる。

を満たすとき、**サイクル**という。
サイクルを持たない有向グラフを**有向非巡回グラフ(directed acyclic graph; DAG)**という。
:::

同値類の遷移グラフはDAGである。
$S$ に対する前順序関係 $\le_T$ を同値類 $S/\sim_T$ についても同様に定義する。
このとき、$\le_T$ は

* (反対称律) $\forall u,v\in S/\sim_T,\,((u\le_T v\land v\le_T u)\implies u=v)$

を満たし、**半順序**関係となる。

::: {.callout-note}
逆に一般の有限半順序集合からDAGを作ることもできる([ハッセ図](https://ja.wikipedia.org/wiki/%E3%83%8F%E3%83%83%E3%82%BB%E5%9B%B3))。
任意のDAGが半順序集合のハッセ図になる訳ではない。
:::

DAGの頂点で出次数(外に出ていく有向辺の個数)が0のものを**シンク**という。
(有限サイズの)DAGは必ずシンクを一つ以上持つ。
一般のマルコフ連鎖の定常分布について、その同値類の遷移グラフを用いて考察する。
マルコフ連鎖の同値類の遷移グラフにおいてシンクに対応する同値類やそれに含まれる状態を**再帰的**であるという。

:::{#lem-stat-trans}
マルコフ連鎖の定常状態を $\mu\in\mathbb{R}^n$ とすると、再帰的でない状態 $s\in S$ について $\mu(s)=0$ である。
:::
:::{.proof}
定常分布 $\mu\in\mathbb{R}^n$ が再帰的でない状態 $s\in S$ について$\mu(s)>0$ であると仮定する。
状態 $s$ に対して再帰的な状態 $t\in S$ が存在して、$s\le_T t$ である。
この再帰的な状態 $t\in S$ が属する同値類を $C$ とおくと、定常分布におけるこの同値類の確率の総和
\begin{align*}
\sum_{s\in C} \mu(s)
\end{align*}
もマルコフ連鎖の遷移によって不変である。
しかし、最初に確率1で$s$に入る状態からマルコフ連鎖をスタートしたとき、十分長いステップ(例えば状態数 $n$)遷移すると必ず正の確率で同値類 $C$ に遷移してしまう。
よって、再帰的な同値類 $C$ の確率の総和は増加してしまう。
これは矛盾であるので、定常分布 $\mu$ において再帰的でない状態 $s\in S$ の確率は0である。
:::

よって、一般のマルコフ連鎖の定常状態を考えるときは、非再帰的な状態を削除してしまって考えてもよい。
このとき、再帰的な同値類 $C_1,C_2,\dotsc,C_k$ は互いに遷移できないので、独立に考えることができる。
それぞれの再帰的な同値類 $C_i$ について、$C_i$ だけに確率を持つ定常分布 $\mu_i$ が唯一存在する。
定常分布は凸集合に閉じているので、
\begin{align*}
\sum_{i=1}^k p_i \mu_i
\end{align*}
も定常分布となる。
逆に $\mu$ が定常分布のとき、それを $C_i$ に制限したものも定常ベクトルになる。よって、それは $\mu_i$ の非負倍に等しい。
