on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Add .venv/bin to PATH (Workaround)
        run: echo "$(pwd)/.venv/bin" >> $GITHUB_PATH
        shell: bash

      - name: Cache TinyTeX directory
        id: cache-tinytex
        uses: actions/cache@v4
        with:
          path: ~/.TinyTeX
          key: tinytex-${{ runner.os }}-${{ hashFiles('tinytex_packages.txt') }}
          restore-keys: |
            tinytex-${{ runner.os }}-

      - name: Install TinyTeX and packages (if cache miss)
        if: steps.cache-tinytex.outputs.cache-hit != 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Cache miss. Installing TinyTeX and packages..."
          quarto install tinytex --update-path --no-prompt --log-level warning
          tlmgr update --self
          tlmgr install $(cat tinytex_packages.txt)

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
